### ISSUE TITLE
Worklist iterative algorithm for data flow analysis

### ISSUE THREAD

**Issue by YahyaAbraheem** [Auxy233/llvm-dataflow-analysis#1]
Hello,

Do you have working version of worklist algorithm for data flow analysis based on kill and gen sets?

**Comment by Auxy233** [comment]
The reaching definition is based on gen/kill set algorithm, not sure if you refer to that

**Comment by YahyaAbraheem** [comment]
Thanks. But what I meant do you have implementation for iterative work list algorithm that runs based on kill and gen sets for any program?

Your implementation is not based on Flex and Bison, right?

**Comment by Auxy233** [comment]
hmmm do you mean that **running some algorithms by given a kill & gen set of a program**?
No, my code is based on LLVM pass, which relies on IR which is parsed by LLVM. And it generates results based on the info from LLVM API. Flex and Bison are not used here.

**Comment by YahyaAbraheem** [comment]
Yeah, worklist algorithm. Worklist algorithm works on top of Gen and Kill sets. Have you written worklist algorithm on top of LLVM?

**Comment by Auxy233** [comment]
Check out in [dataflow.cpp](https://github.com/Auxy233/llvm-dataflow-analysis/blob/master/dataflow/Dataflow.cpp). Worklist algorithm is more like a basic framework, and you need to create own `Join` and `Transfer` function
